### ISSUE TITLE
Example GaMMA + SeisBench

### ISSUE THREAD

**Issue by yetinam** [AI4EPS/GaMMA#13]
Hi!
We've built an example using GaMMA together with SeisBench to quickly create a seismicity catalog with data from an FDSN webservice. You can find it [here](https://github.com/seisbench/seisbench/blob/main/examples/03c_catalog_seisbench_gamma.ipynb) and also run it on [Google Colab](https://colab.research.google.com/github/seisbench/seisbench/blob/main/examples/03c_catalog_seisbench_gamma.ipynb). I was wondering whether you'd maybe like to add it to the list of examples in this repo and/or your documentation?

**Comment by wayneweiqiang** [comment]
Thank you for sharing this example! I have added it to the documentation: https://wayneweiqiang.github.io/GaMMA/example_seisbench/

**Comment by yetinam** [comment]
Thanks!
