### ISSUE TITLE
Differences when reproducing example

### ISSUE THREAD

**Issue by Cthuulhaa** [AI4EPS/GaMMA#15]
Hello! I tried to reproduce the example using synthetic data in the documentation and the result I obtained was different (and actually incorrect, because it associated picks to additional, non existent events). A copy-paste of the code produced the same incorrect result. Any ideas on what could be causing this difference? Maybe using a different version of any of the dependencies?

![Figure_1](https://user-images.githubusercontent.com/81183635/181487328-e99b82ed-60e5-42fe-8db1-42d9beed7629.png)

`True events:`
`loc=400.000	t0=33.333	mag=2.000`
`loc=1600.000	t0=93.333	mag=2.352`
`loc=880.000	t0=153.333	mag=2.169`
`loc=1360.000	t0=213.333	mag=2.551`
`loc=1120.000	t0=273.333	mag=2.766`
`loc=640.000	t0=333.333	mag=3.000`
`GMMA time = 0.5283012390136719`

`Associated events:`
`loc=400.0	t0=33.3	mag=2.0	sigma11=0.495`
`loc=1517.6	t0=77.4	mag=4.2	sigma11=0.358`
`loc=1600.0	t0=93.3	mag=2.4	sigma11=0.185`
`loc=880.0	t0=153.3	mag=2.2	sigma11=0.161`
`loc=1360.0	t0=213.3	mag=3.1	sigma11=0.088`
`loc=1120.0	t0=273.3	mag=2.8	sigma11=0.098`
`loc=498.1	t0=292.0	mag=3.3	sigma11=0.600`
`loc=877.6	t0=372.9	mag=2.2	sigma11=1.197`

Cheers!

**Comment by wayneweiqiang** [comment]
Hi, I may have broken this test during updates. It works for me now. Can you try again?
