### ISSUE TITLE
About sigma parameters

### ISSUE THREAD

**Issue by ecastillot** [AI4EPS/GaMMA#16]
Hi!

I don't understand very well the purpose of sigma parameters. Could you explain me them please?
- max_sigma11
- max_sigma22
- max_sigma12

I am using GaMMA to associate seismic events in a regional network, I have noticed that by setting the max_sigma11=20 parameter, I have more associations than max_sigma11=2 (default parameter).

**Comment by wayneweiqiang** [comment]
Hi, I have added the meaning of these parameters in the README file.
