### ISSUE TITLE
All magnitudes are coming out ~8

### ISSUE THREAD

**Issue by wagnerk-89** [AI4EPS/GaMMA#17]
All magnitudes are coming out as ~8 (>1000 events in a one month period). I'm unclear how Gamma is calculating the magnitudes and what I can adjust to make this come out correctly. Running other datasets through the same workflow results in proper magnitudes that are close to what is in their catalogues.

**Comment by zhuwq0** [comment]
Hi, Please check if the unit of the input picks are m/s (PGV). As we explained in the paper, we use a simple GMPE to estimate the magnitude.
