### ISSUE TITLE
Bug: ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by ecastillot** [AI4EPS/GaMMA#18]
Dear Weiqiang,

Sometimes I have gotten an unexpected error when I tried to associate some seismic phases. If you want to reproduce the error,  I attached both picks and stations csv. 
[picks.csv](https://github.com/AI4EPS/GaMMA/files/9758536/picks.csv)
[stations.csv](https://github.com/AI4EPS/GaMMA/files/9758537/stations.csv)

This is the error:

`File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/gamma/_bayesian_mixture.py", line 526, in _initialize
    self._estimate_precisions(nk, xk, sk)
  File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/gamma/_bayesian_mixture.py", line 584, in _estimate_precisions
    self.covariances_, self.covariance_type, self.max_covar)
  File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/gamma/_gaussian_mixture.py", line 484, in _compute_precision_cholesky
    cov_chol = linalg.cholesky(covariance, lower=True)
  File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 91, in cholesky
    check_finite=check_finite)
  File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/scipy/linalg/decomp_cholesky.py", line 19, in _cholesky
    a1 = asarray_chkfinite(a) if check_finite else asarray(a)
  File "/home/emmanuel/anaconda3/envs/eqt/lib/python3.7/site-packages/numpy/lib/function_base.py", line 489, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs`

And the input parameters are:
`
x(km)= array([  674.5275551 ,  1777.84677595]),
y(km)= array([  491.76753437,  1605.99660826]), 
z(km)= array([  0, 180]),
bfgs_bounds= ((673.52755510494535, 1778.846775953371), (490.76753436815903, 1606.996608260825), (0, 181), (None, None)
use_dbscan=False,
use_amplitude=False,
dbscan_eps=10.0,
dbscan_min_samples=3,
vel = {"p": 7.0, "s": 7.0 / 1.75},
method="BGMM",
oversample_factor=20,
min_picks_per_eq=5,
max_sigma11=2.0,
max_sigma22=1.0,
max_sigma12=1.0,
`

This error only has happened sometimes, in other picks data GaMMA works properly. Do you know what could be the error? or is there something I am doing wrong?
Thanks for your help.
Regards

**Comment by zhuwq0** [comment]
Hi, could you share the script to reproduce this error? It seems you are working with a large area but a few picks.

**Comment by ecastillot** [comment]
[gamma.zip](https://github.com/AI4EPS/GaMMA/files/9864436/gamma.zip)
Sure, 
I attach the script. Let me know if you have problems to reproduce the error.
Thanks.

**Comment by zhuwq0** [comment]
Thank you for sharing the script. I have fixed the Nan error in the latest version. Could you please help have a check?

**Comment by ecastillot** [comment]
It works properly. So, I am going to close this issue.
Thanks Weiqiang!!
