### ISSUE TITLE
ValueError when disabling DBSCAN

### ISSUE THREAD

**Issue by ziyixi** [AI4EPS/GaMMA#23]
As shown below, when we are in the else branch (`config["use_dbscan"]=False`), L73 will try to remove -1 in `unique_labels`. And it will raise `ValueError: list.remove(x): x not in list`.

https://github.com/AI4EPS/GaMMA/blob/067893cd275f3e768b08eb2df878b50a3cc76238/gamma/utils.py#L70-L73

**Comment by zhuwq0** [comment]
Fixed now. Thanks
