### ISSUE TITLE
Limit on number of picks and GaMMA inside a loop

### ISSUE THREAD

**Issue by OliviaPS** [AI4EPS/GaMMA#24]
Hi,

I have been using GaMMA to associate some of the automatic picks I have and it has worked well. Now I want to use it for the thousands of picks that I have from years of data. 

Is there a la limit to the number of picks GaMMA can input? I tried putting the GaMMA association inside a loop but after a few times it does not process the data frame completely, so I am thinking of doing big batches of picks.

Any recommendations on how to use GaMMA with a really large number of picks will be really appreciated!

Olivia PS

**Comment by zhuwq0** [comment]
What do you mean "not process the data frame completely"? There is not a limit of the number of picks as long as DBSCAN can segment the whole list.

**Comment by OliviaPS** [comment]
I have the association function inside a loop that reads chunks of a very large csv file with thousands of picks. If I send to GaMMA chunks of 500 picks, by the 7th time GaMMA says: "Process [467, 438, 465, 488, 479, etc] picks: ....."
For the firsts chunks, it says "Process 500 picks: " and I have also made sure that the data frame of 500 picks is always 500 picks. I have found no pattern in the number of picks GaMMA decides to process after a few chunks. 
This has happened using different chunks sizes, even after a few chunks of 2000 picks.

**Comment by zhuwq0** [comment]
You can turn off DBSCAN if you chunk picks by yourself.

**Comment by OliviaPS** [comment]
I changed use_DBSCAN to False and I still had the issue. Then, I updated the package and I get this error when trying to run GaMMA: 

File "gamma_run.py", line 327, in <module>
    method=config["method"])
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/site-packages/gamma/utils.py", line 85, in association
    p.starmap(associate, [[data[labels == k], locs[labels == k], phase_type[labels == k], phase_weight[labels == k], pick_idx[labels==k], pick_station_id[labels==k], config, timestamp0, vel, method, events, assignment, event_idx, lock] for k in unique_labels])
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/home/pitaslol/miniconda/envs/gamma/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in pyproj._transformer._Transformer.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__


I have not changed the code, do you know what could be happening? Thank you!

**Comment by zhuwq0** [comment]
Are you running this example: https://ai4eps.github.io/GaMMA/example_phasenet/? If not, please try this example first, then you can follow this example to process your data.

**Comment by OliviaPS** [comment]
I used the Seisbench example as the base for my code. I will try the Phasenet example and see how that goes. Thanks!

**Comment by zhuwq0** [comment]
I did a quick test of the seisbench example. It is running correctly on my machine.

**Comment by zhuwq0** [comment]
I turned off multiprocessing when not using DBSCAN. Maybe that solve your problem. Please have a try using the new code on github.

**Comment by OliviaPS** [comment]
I created a new conda environment and used the updated version and my code runs now! Thank you!!
Using DBSCAN is also much faster than before!  Not using DBSCAN is really slow now, so I think I will use DBSCAN and I might not even need to do it in chunks.

Thank you for the help!

**Comment by zhuwq0** [comment]
Great.
