### ISSUE TITLE
Torch dependency

### ISSUE THREAD

**Issue by martijnende** [AI4EPS/GaMMA#25]
Hi Weiqiang. Thanks for maintaining this useful code repository. I wanted to give GaMMA a try, but it seems that the dependency list is not up-to-date. `seismic_ops` includes `torch` as a dependency, which is missing from `requirements.txt`. Also, would it be possible to make this an optional dependency? Getting PyTorch to play nice alongside TensorFlow and JAX is practically impossible, especially with GPU support, so GaMMA would not be compatible with most of my environments. Is the Eikonal solver an essential part of the `BayesianGaussianMixture` routine?

**Comment by zhuwq0** [comment]
Hi Martijn, it is great to hear from you. Thanks for your suggestions. This is a recent contribution from one student to add an eikonal solver. I just add a try-except to remove the dependency of pytorch. Pytorch is not part of the BayesianGaussianMixture if not using the eikonal solver.

**Comment by martijnende** [comment]
Thanks for the quick fix! I'll give it a try
