### ISSUE TITLE
Shallow false detections

### ISSUE THREAD

**Issue by yetinam** [AI4EPS/GaMMA#31]
Hi Weiqiang,

I've been testing GaMMA in different scenarios lately. In general, it works really well, but I noticed that I often get very shallow (<5 km) false detections. I put a picture below with an example. Some of the very shallow seismicity is real but there are also a lot of false detections. I've tried this with different pickers and in different regions. Do you have any ideas how these shallow false detections can be explained and how to avoid them?

![image](https://user-images.githubusercontent.com/14940857/229790716-736b0c0f-fd13-48bc-be1a-d71bb46e03ee.png)

**Comment by zhuwq0** [comment]
Hi Jannes, I agree this situation is common in association. One reason is the location in association is not accurate, and I initialize all event locations on the surface: https://github.com/AI4EPS/GaMMA/blob/47446d988e2697a6ca794c93deb0f0281d12f0fd/gamma/utils.py#L356. The depth is known to be hard to constrain with a few picks, so these shallow events are mostly because the depth can not be constrained. These shallow events can be adjusted or removed during re-location.

**Comment by yetinam** [comment]
Hi Weiqiang,
thanks for the quick reply! I was anyhow planning to do relocation, so let's see how it'll look afterwards. I'll close the issue for now but I might update it once I got around to do relocation.

**Comment by yetinam** [comment]
Just for completeness, relocation indeed did wonders. Below is the output after using NonLinLoc on the outputs (and slightly increasing the threshold in the number of picks). Mind the different scaling of the y-axis and colorbar compared to the previous plot.

![image](https://user-images.githubusercontent.com/14940857/230579701-948aff8c-86b4-4ee7-a5d3-f786e2259333.png)

**Comment by zhuwq0** [comment]
Hi Jannes, thanks for sharing the updates! My current test examples are quite shallow. If possible, could you contribute this example to the repository? I think others may also be testing deep earthquakes. I forgot to mention another thing you can try is the "initial_points". The default is [1,1,1] meaning the number of initialization points along x, y, z. You can try adding more points along z axis. You can pass other values to the config dict.

**Comment by yetinam** [comment]
It's actually the same example as in the SeisBench example notebook, just for a longer time period (1 month). The NonLinLoc integration is pretty messy, so I can't really share that part for now. I'll also try playing around with further points in z direction. Thanks for the hint!
