### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'float' and 'str' when running association

### ISSUE THREAD

**Issue by dsindija** [AI4EPS/GaMMA#34]
Hi, when I run association on my own dataset I get this error:

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/utils.py", line 193, in associate
    gmm = BayesianGaussianMixture(
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/_base.py", line 204, in fit
    self.fit_predict(X, y)
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/_base.py", line 249, in fit_predict
    self._initialize_parameters(X, random_state)
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/_base.py", line 162, in _initialize_parameters
    resp, centers, means = initialize_centers(X, self.phase_type, self.centers_init, self.station_locs, random_state)
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/seismic_ops.py", line 430, in initialize_centers
    means[i, :, :] = calc_time(centers_init[i : i + 1, :], station_locs, phase_type)
  File "/home/dinko/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/seismic_ops.py", line 141, in calc_time
    tt = np.linalg.norm(ev_loc - station_loc, axis=-1, keepdims=True) / v + ev_t
TypeError: unsupported operand type(s) for -: 'float' and 'str'
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[73], line 2
      1 assigments=[]
----> 2 catalogs, assignments = association(pick_df, station_df, config, method=config["method"])
      4 catalog = pd.DataFrame(catalogs)
      5 assignments = pd.DataFrame(assignments, columns=["pick_idx", "event_idx", "prob_gamma"])

File ~/anaconda3/envs/seisbench/lib/python3.9/site-packages/gamma/utils.py:113, in association(picks, stations, config, event_idx0, method, **kwargs)
    111 chunk_size = max(len(unique_labels)//(config["ncpu"]*20), 1)
    112 with mp.get_context('spawn').Pool(config["ncpu"]) as p:
--> 113     results = p.starmap(
    114         associate,
    115         [
    116             [
    117                 k,
    118                 labels,
    119                 data,
    120                 locs,
    121                 phase_type,
    122                 phase_weight,
    123                 pick_idx,
    124                 pick_station_id,
    125                 config,
    126                 timestamp0,
    127                 vel,
    128                 method,
    129                 event_idx,
    130                 lock,
    131             ]
    132             for k in unique_labels
    133         ],
    134         chunksize=chunk_size,
    135     )
    136     # resuts is a list of tuples, each tuple contains two lists events and assignment
    137     # here we flatten the list of tuples into two lists
    138     events, assignment = [],[]

File ~/anaconda3/envs/seisbench/lib/python3.9/multiprocessing/pool.py:372, in Pool.starmap(self, func, iterable, chunksize)
    366 def starmap(self, func, iterable, chunksize=None):
    367     '''
    368     Like `map()` method but the elements of the `iterable` are expected to
    369     be iterables as well and will be unpacked as arguments. Hence
    370     `func` and (a, b) becomes func(a, b).
    371     '''
--> 372     return self._map_async(func, iterable, starmapstar, chunksize).get()

File ~/anaconda3/envs/seisbench/lib/python3.9/multiprocessing/pool.py:771, in ApplyResult.get(self, timeout)
    769     return self._value
    770 else:
--> 771     raise self._value

TypeError: unsupported operand type(s) for -: 'float' and 'str'
__________________________________________________________

I based my example on seisbench example, which works fine on my machine.
I also compared my "pick_df" and "station_df" with the seisbench example and everything that is supposed to be a string is a string and what's float is a float. Could you please point out where I cause this error to be raised?

Here is how I define my config variable:

config = {}
config["dims"] = ['x(km)', 'y(km)', 'z(km)']
config["use_dbscan"] = True
config["use_amplitude"] = False
config["x(km)"] = (250, 850)
config["y(km)"] = (4500, 5800)
config["z(km)"] = (0, 30)
config["vel"] = {"p": 6.0, "s": 6.0 / 1.75}  
config["method"] = "BGMM"
if config["method"] == "BGMM":
    config["oversample_factor"] = 4
if config["method"] == "GMM":
    config["oversample_factor"] = 1

 
config["bfgs_bounds"] = (
    (config["x(km)"][0] - 1, config["x(km)"][1] + 1),  # x
    (config["y(km)"][0] - 1, config["y(km)"][1] + 1),  # y
    (0, config["z(km)"][1] + 1),  # x
    (None, None),  # t
)
config["dbscan_eps"] = 12  # seconds
config["dbscan_min_samples"] = 5

config["min_picks_per_eq"] = 5
config["min_p_picks_per_eq"] = 0
config["min_s_picks_per_eq"] = 0
config["max_sigma11"] = 6.0
config["max_sigma22"] = 1.0
config["max_sigma12"] = 1.0

config["ncpu"]=12

for k, v in config.items():
    print(f"{k}: {v}")

**Comment by zhuwq0** [comment]
Hi, is the lat/lon of your station_df a string?

**Comment by dsindija** [comment]
Yes, it turned out they were. Thought I checked it properly but I didn't in the end. Silly of me. 
Everything works fine now. Thanks!
