### ISSUE TITLE
Add validate argument to untils.py

### ISSUE THREAD

**Issue by mihtm13** [AI4EPS/GaMMA#39]
Hello there,
I started with GaMMA and after my first Error prompts I noticed that maybe there is one small enhancement for the utils.py in function convert_picks_to_csv in line 46:
   ```
    meta = stations.merge(picks["id"], how="right", on="id")
```
to 
```
    meta = stations.merge(picks["id"], how="right", on="id", validate="one_to_many")
```
In that way you can make sure that there are no duplicates in stations DataFrame. 

I hope that's an improvement.

Best regards

**Comment by zhuwq0** [comment]
Thanks. I did not know this argument. I will add that.
