### ISSUE TITLE
False Detections

### ISSUE THREAD

**Issue by JanisHe** [AI4EPS/GaMMA#40]
Hi Weiqiang,

in your paper you write "it is challenging to evaluate the false positive associations in these catalogs." 
Do you have any idea/solution to get rid of these false positive associations?

Thanks
Janis

In case you don't like to answer publicly: janis.heuel(at)rub.de

**Comment by zhuwq0** [comment]
There is a trade-off between false positives and false negatives. You can increase the filtering criteria to reduce false positives, but that will also increase false negatives.
