### ISSUE TITLE
**use_amplitude** parameter guidance

### ISSUE THREAD

**Issue by iqram1337** [AI4EPS/GaMMA#45]
1. Why i can't turn on **use_amplitude** parameter with chile region in example notebook?

2. In the other hand, i have tried using 1 event with 6 stations (3 components), but when I compare it with the original event information, the magnitude of the gamma generated is 8 (always 8 even if the dbscan parameter is changed repeatedly), whereas it should be 3.5. **When i turn off turn use_amplitude the gamma standard_catalog return nothing, 0 event**

**Comment by zhuwq0** [comment]
Hi, 
1. the chile example does not have "phase_amplitude" in the phase file.
2. Can you check your phase_amplitude (in PGV, m/s) is normal?

**Comment by iqram1337** [comment]
> Hi,
> 
> 1. the chile example does not have "phase_amplitude" in the phase file.
> 2. Can you check your phase_amplitude (in PGV, m/s) is normal?

how to check the units? i honestly no idea what the unit is. The amplitude is just straight output from the PhaseNet. Please help me with this. thank you
