### ISSUE TITLE
Picks ID

### ISSUE THREAD

**Issue by Cthuulhaa** [AI4EPS/GaMMA#48]
Hi,

I utilized GaMMA to associate some picks to one event. This is the Pandas dataframe of my picks:

            id             timestamp            prob      type
     0    SX.MUHB  2018-01-02 08:25:31.980000  0.408322    p
     1    SX.WIMM  2018-01-02 08:25:29.530000  0.375889    p
     2    SX.WIMM  2018-01-02 08:25:34.940000  0.380612    s
     3    TH.CHRS  2018-01-02 08:25:33.010000  0.893861    p
     4    TH.CHRS  2018-01-02 08:25:41.290000  0.575885    s
     5   TH.NEUST  2018-01-02 08:25:32.920000  0.779552    p
     6   TH.NEUST  2018-01-02 08:25:40.550000  0.649434    s
     7    SX.NEUB  2018-01-02 08:25:34.010000  0.316887    p
     8    SX.NEUB  2018-01-02 08:25:44.970000  0.377629    s
     9     GR.CLZ  2018-01-02 08:25:37.040000  0.397447    p
    10    GR.CLZ  2018-01-02 08:25:47.950000  0.204681    s
    11   TH.POSS  2018-01-02 08:25:35.960000  0.804459    p
    12   TH.POSS  2018-01-02 08:25:46.740000  0.529056    s
    13   TH.TAUT  2018-01-02 08:25:38.150000  0.371234    p
    14   TH.TAUT  2018-01-02 08:25:51.690000  0.396445    s

and this is the output of picks associated to the event (following the SeisBench example):

             pick_idx  event_idx  prob_gamma
     0          1          1       0.000921
     1          2          1       0.073889
     2          3          1       0.069758
     3          4          1       0.174539
     4          5          1       0.113167
     5          6          1       0.151336
     6          7          1       0.110181
     7          8          1       0.061309
     8          9          1       0.042372
     9         11          1       0.066970
    10        12          1       0.013890
    11        13          1       0.143820

This might be obvious, but my question is, to which pick on my picks dataframe do the indexes in the pick_idx column correspond? For example, pick_idx 1 corresponds to the pick with id SX.WIMM (type p) or to SX.MUHB (type p).

Thanks in advance for the help!

**Comment by SquirrelKnight** [comment]
The pick index corresponds to the row number in your pick dataframe. You can merge together the tables based on in the pick_idx column. Assuming 'assignments' is your association output, and pick_df is you picks dataframe, do the following:

```
assignments[['id','timestamp','prob','type']] = pick_df.loc[assignments.pick_idx.values,['id','timestamp','prob','type']].values
assignments.sort_values('timestamp',inplace=True)
```

**Comment by Cthuulhaa** [comment]
@SquirrelKnight thanks for answering! :)
